name: A workflow to see the usage of environment variables
on: [push, create]

jobs:      
  weekday_job:
    runs-on: ubuntu-latest
    env:
      DAY_OF_WEEK: Mon            ## JOB LEVEL Environment variable
    steps:
      - name: "Checking the day of week"
        if: env.DAY_OF_WEEK == 'Mon'
        run: echo "Hello $FIRST_NAME $Last_NAME $USERNAME $PASSWORD, today is Monday!"
        env:
          FIRST_NAME: Mona                ## STEP LEVEL Environment variable
          Last_NAME: Octocat
          USERNAME: ${{ secrets.USERNAME }}               ## ENCRYPTED SECRET ENVIRONMENT VARIABLES
          PASSWORD: ${{ secrets.PASSWORD }}  
