name: Getting the secrets
on: push
jobs:
  access_the_secret:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}  
      NAME: Octocat
    steps:
    - run: echo "the username is $env.USERNAME $env.PASSWORD $env.NAME"
