name: Getting the secrets
on: push
jobs:
  access_the_secret:
    runs-on: ubuntu-latest
    env:
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}  
    steps:
    - run: echo "the username is $env.USERNAME"

  my-job:
    name: Decrypt and Print Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.USERNAME }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret
        run: echo "The secret is env.LARGE_SECRET_PASSPHRASE"
